#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: setup-server.sh --yes [options]

Options:
  --yes                    Confirm filesystem changes.
  --force                 Replace files in the selected isolated paths.
  --no-systemd            Generate the unit but do not install/start it.
  --server-binary PATH    Existing twokitties-server binary to install.
  --install-dir PATH      Binary directory (default: /opt/twokitties).
  --data-dir PATH         Database/TLS directory (default: /var/lib/twokitties).
  --config-dir PATH       Configuration directory (default: /etc/twokitties).
  --listen-addr ADDRESS   Listen address written to config (default: 0.0.0.0:9443).
  --help                  Show this help.
EOF
}

YES=0
FORCE=0
NO_SYSTEMD=0
SERVER_BINARY=""
INSTALL_DIR=/opt/twokitties
DATA_DIR=/var/lib/twokitties
CONFIG_DIR=/etc/twokitties
LISTEN_ADDR=0.0.0.0:9443

while (($#)); do
  case "$1" in
    --yes) YES=1; shift ;;
    --force) FORCE=1; shift ;;
    --no-systemd) NO_SYSTEMD=1; shift ;;
    --server-binary) SERVER_BINARY=${2:?missing path after --server-binary}; shift 2 ;;
    --install-dir) INSTALL_DIR=${2:?missing path after --install-dir}; shift 2 ;;
    --data-dir) DATA_DIR=${2:?missing path after --data-dir}; shift 2 ;;
    --config-dir) CONFIG_DIR=${2:?missing path after --config-dir}; shift 2 ;;
    --listen-addr) LISTEN_ADDR=${2:?missing address after --listen-addr}; shift 2 ;;
    --help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if ((YES != 1)); then
  echo 'Refusing to modify the filesystem without --yes.' >&2
  exit 2
fi

if [[ -z "$SERVER_BINARY" ]]; then
  script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
  SERVER_BINARY="$script_dir/../target/release/twokitties-server"
fi

for required in "$SERVER_BINARY"; do
  [[ -f "$required" && -x "$required" ]] || { echo "server binary is missing or not executable: $required" >&2; exit 1; }
done

if ((FORCE == 0)) && {
  [[ -e "$INSTALL_DIR/twokitties-server" ]] || [[ -e "$CONFIG_DIR/server.env" ]] || [[ -e "$DATA_DIR/twokitties.db" ]];
}; then
  echo 'An installation already exists in the selected paths; use --force with explicit paths to replace it.' >&2
  exit 1
fi

command -v openssl >/dev/null || { echo 'openssl is required to generate local TLS material.' >&2; exit 1; }
command -v python3 >/dev/null || { echo 'python3 is required to initialize SQLite.' >&2; exit 1; }

mkdir -p -- "$INSTALL_DIR" "$DATA_DIR/tls" "$CONFIG_DIR"
install -m 0755 -- "$SERVER_BINARY" "$INSTALL_DIR/twokitties-server"

DB_PATH="$DATA_DIR/twokitties.db"
TLS_CERT="$DATA_DIR/tls/server.crt"
TLS_KEY="$DATA_DIR/tls/server.key"
if [[ ! -e "$TLS_CERT" || ! -e "$TLS_KEY" || $FORCE == 1 ]]; then
  openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
    -subj '/CN=twokitties-self-hosted' \
    -addext 'basicConstraints=critical,CA:FALSE' \
    -addext 'keyUsage=critical,digitalSignature,keyEncipherment' \
    -addext 'extendedKeyUsage=serverAuth' \
    -addext 'subjectAltName=DNS:twokitties-self-hosted,IP:127.0.0.1' \
    -keyout "$TLS_KEY" -out "$TLS_CERT" >/dev/null 2>&1
  chmod 600 -- "$TLS_KEY"
  chmod 644 -- "$TLS_CERT"
fi

python3 - "$DB_PATH" <<'PY'
import sqlite3
import sys
connection = sqlite3.connect(sys.argv[1])
connection.execute("""
CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)
""")
connection.commit()
connection.close()
PY
chmod 600 -- "$DB_PATH"

cat > "$CONFIG_DIR/server.env" <<EOF
# Generated by setup-server.sh. Keep this file private.
LISTEN_ADDR=$LISTEN_ADDR
DATABASE_PATH=$DB_PATH
TLS_CERT_PATH=$TLS_CERT
TLS_KEY_PATH=$TLS_KEY
EOF
chmod 600 -- "$CONFIG_DIR/server.env"

cat > "$CONFIG_DIR/twokitties.service" <<EOF
[Unit]
Description=TwoKitties server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=twokitties
Group=twokitties
EnvironmentFile=$CONFIG_DIR/server.env
ExecStart=$INSTALL_DIR/twokitties-server
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=$DATA_DIR

[Install]
WantedBy=multi-user.target
EOF
chmod 644 -- "$CONFIG_DIR/twokitties.service"

if [[ $(id -u) -eq 0 ]] && command -v useradd >/dev/null; then
  if ! id twokitties >/dev/null 2>&1; then
    useradd --system --home-dir "$DATA_DIR" --shell /usr/sbin/nologin twokitties
  fi
  chown -R twokitties:twokitties -- "$DATA_DIR"
  chown root:twokitties -- "$CONFIG_DIR" "$CONFIG_DIR/server.env" "$CONFIG_DIR/twokitties.service"
  chmod 750 -- "$CONFIG_DIR"
fi

if ((NO_SYSTEMD == 0)); then
  if [[ $(id -u) -eq 0 ]] && command -v systemctl >/dev/null; then
    install -m 0644 -- "$CONFIG_DIR/twokitties.service" /etc/systemd/system/twokitties.service
    systemctl daemon-reload
    systemctl enable twokitties.service
    echo 'Generated and enabled systemd service. Start it with: systemctl start twokitties'
  else
    echo 'Generated systemd unit; root/systemctl were unavailable, so it was not installed.'
  fi
else
  echo 'Generated systemd unit without installing or starting it (--no-systemd).'
fi

echo "Installed binary: $INSTALL_DIR/twokitties-server"
echo "Configuration: $CONFIG_DIR/server.env"
echo "Database: $DB_PATH"
echo "TLS certificate: $TLS_CERT"
echo 'Warning: the generated certificate is self-signed for initial testing; use a trusted certificate before public deployment.'
