[package]
name = "twokitties-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
argon2 = "0.5"
twokitties-protocol = { path = "../protocol" }
rand_core = { version = "0.6", features = ["getrandom"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2"
rusqlite = { version = "0.32", features = ["bundled"] }

[dev-dependencies]
rcgen = "0.13"

[lib]
path = "src/lib.rs"

[[bin]]
name = "twokitties-server"
path = "src/main.rs"
